/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import domain.Zaposleni;
import javax.swing.JOptionPane;

/**
 *
 * @author Jelena
 */
public class FrmPocetna extends javax.swing.JFrame {

    /**
     * Creates new form FrmPocetna
     */
    public FrmPocetna() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIme = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        brnIzloguj = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miDodajLovca1 = new javax.swing.JMenuItem();
        miDodajLovca = new javax.swing.JMenuItem();
        miDodajTIm = new javax.swing.JMenu();
        miPrikazTimova = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        miDodajDivljac = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miDodajTermin = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        miPrikazZakazivanja = new javax.swing.JMenuItem();
        miZakaziTermin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 86, 40));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MUDDY BOOT SRB");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacije o trenutno prijavljenom zaposlenom"));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Ime:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Prezime:");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Korisnicko ime:");

        txtIme.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtIme.setText("IME");

        txtPrezime.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtPrezime.setText("PREZIME");

        txtUsername.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtUsername.setText("KORISNICKO IME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsername))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        brnIzloguj.setBackground(new java.awt.Color(69, 86, 40));
        brnIzloguj.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        brnIzloguj.setForeground(new java.awt.Color(255, 255, 255));
        brnIzloguj.setText("Izloguj se");
        brnIzloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnIzlogujActionPerformed(evt);
            }
        });

        jMenu1.setText("Lovac");

        miDodajLovca1.setText("Prikaži lovce");
        miDodajLovca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajLovca1ActionPerformed(evt);
            }
        });
        jMenu1.add(miDodajLovca1);

        miDodajLovca.setText("Dodaj lovca");
        miDodajLovca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajLovcaActionPerformed(evt);
            }
        });
        jMenu1.add(miDodajLovca);

        jMenuBar1.add(jMenu1);

        miDodajTIm.setText("Tim");

        miPrikazTimova.setText("Prikaži timove");
        miPrikazTimova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrikazTimovaActionPerformed(evt);
            }
        });
        miDodajTIm.add(miPrikazTimova);

        jMenuItem2.setText("Dodaj tim");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        miDodajTIm.add(jMenuItem2);

        jMenuBar1.add(miDodajTIm);

        jMenu3.setText("Divljač");

        jMenuItem1.setText("Prikaži divljači");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        miDodajDivljac.setText("Dodaj divljač");
        miDodajDivljac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajDivljacActionPerformed(evt);
            }
        });
        jMenu3.add(miDodajDivljac);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Termini");

        miDodajTermin.setText("Dodaj Termin");
        miDodajTermin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajTerminActionPerformed(evt);
            }
        });
        jMenu4.add(miDodajTermin);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Zakazi");

        miPrikazZakazivanja.setText("Prikaži zakazivanja");
        miPrikazZakazivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrikazZakazivanjaActionPerformed(evt);
            }
        });
        jMenu5.add(miPrikazZakazivanja);

        miZakaziTermin.setText("Zakaži termin");
        miZakaziTermin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miZakaziTerminActionPerformed(evt);
            }
        });
        jMenu5.add(miZakaziTermin);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(brnIzloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brnIzloguj)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnIzlogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnIzlogujActionPerformed
        Zaposleni ulogovani = Controller.getInstance().getUlogovaniZaposleni();
        Object[] opcije = {"Da", "Ne"};
        String poruka = "Da li ste sigurni da zelite da se odjavite?";
        int izbor = JOptionPane.showOptionDialog(this, poruka, "Kraj rada", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcije, opcije[0]);
        if (izbor == 1) {
            return;
        }
        Controller.getInstance().logout(ulogovani);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_brnIzlogujActionPerformed

    private void miDodajLovcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajLovcaActionPerformed
        FrmUnosLovca formaZaUnosLovca = new FrmUnosLovca(this, true);
        formaZaUnosLovca.setLocationRelativeTo(null);
        formaZaUnosLovca.setVisible(true);
    }//GEN-LAST:event_miDodajLovcaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmUnosTima formaZaUnosTima = new FrmUnosTima(this, true);
        formaZaUnosTima.setLocationRelativeTo(null);
        formaZaUnosTima.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void miZakaziTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miZakaziTerminActionPerformed
        FrmUnosZakazivanja formaZaUnosZakazivanja = new FrmUnosZakazivanja(this, true);
        formaZaUnosZakazivanja.setLocationRelativeTo(null);
        formaZaUnosZakazivanja.setVisible(true);
    }//GEN-LAST:event_miZakaziTerminActionPerformed

    private void miDodajTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajTerminActionPerformed
        FrmUnosTermina formaZaUnosTermina = new FrmUnosTermina(this, true);
        formaZaUnosTermina.setLocationRelativeTo(null);
        formaZaUnosTermina.setVisible(true);
    }//GEN-LAST:event_miDodajTerminActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmPrikazDivljaci formaDivljac = new FrmPrikazDivljaci(this, true);
        formaDivljac.setLocationRelativeTo(null);
        formaDivljac.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miDodajLovca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajLovca1ActionPerformed
        FrmPrikazLovaca formaZaPrikazLovaca = new FrmPrikazLovaca(this, true);
        formaZaPrikazLovaca.setLocationRelativeTo(null);
        formaZaPrikazLovaca.setVisible(true);     }//GEN-LAST:event_miDodajLovca1ActionPerformed

    private void miPrikazTimovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrikazTimovaActionPerformed
        FrmPrikazTimova formaZaPrikazTimova = new FrmPrikazTimova(this, true);
        formaZaPrikazTimova.setLocationRelativeTo(null);
        formaZaPrikazTimova.setVisible(true);     }//GEN-LAST:event_miPrikazTimovaActionPerformed

    private void miPrikazZakazivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrikazZakazivanjaActionPerformed
        FrmPrikazZakazivanja formaZaPrikazZakazivanja = new FrmPrikazZakazivanja(this, true);
        formaZaPrikazZakazivanja.setLocationRelativeTo(null);
        formaZaPrikazZakazivanja.setVisible(true);
       }//GEN-LAST:event_miPrikazZakazivanjaActionPerformed

    private void miDodajDivljacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajDivljacActionPerformed
        FrmUnosDivljaci formaZaUnosDivljaci = new FrmUnosDivljaci(this, true);
        formaZaUnosDivljaci.setLocationRelativeTo(null);
        formaZaUnosDivljaci.setVisible(true);
    }//GEN-LAST:event_miDodajDivljacActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnIzloguj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem miDodajDivljac;
    private javax.swing.JMenuItem miDodajLovca;
    private javax.swing.JMenuItem miDodajLovca1;
    private javax.swing.JMenu miDodajTIm;
    private javax.swing.JMenuItem miDodajTermin;
    private javax.swing.JMenuItem miPrikazTimova;
    private javax.swing.JMenuItem miPrikazZakazivanja;
    private javax.swing.JMenuItem miZakaziTermin;
    private javax.swing.JLabel txtIme;
    private javax.swing.JLabel txtPrezime;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        txtIme.setText(Controller.getInstance().getUlogovaniZaposleni().getIme());
        txtPrezime.setText(Controller.getInstance().getUlogovaniZaposleni().getPrezime());
        txtUsername.setText(Controller.getInstance().getUlogovaniZaposleni().getUsername());
    }
}
